<a href="https://colab.research.google.com/github/Mradul2k04/Machine_Learning/blob/Linear_Algebra/Basic_Leaner_and__Matrix_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [2]:
df=pd.read_csv("/content/hdfc_loan_dataset_full_enriched - hdfc_loan_dataset_full_enriched.csv")

In [3]:
df

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,HDFC100996,HDFC Bank,Simran Kaur,Male,Yes,1,Graduate,Salaried,44713,0,...,10.965,Neutral,Sikh,Tamil Nadu,Coimbatore,6635,3.830000e+11,9350952889,simran.kaur@example.in,Medical Representative
996,HDFC100997,HDFC Bank,Krishna Mehta,Male,No,2,Graduate,Salaried,70886,0,...,3.268,Negative,Hindu,Kerala,Trivandrum,217843,7.040000e+11,9176504718,krishna.mehta@example.in,Customer Support Executive
997,HDFC100998,HDFC Bank,Rohan Verma,Female,No,1,Graduate,Salaried,24392,11337,...,0.703,Positive,Hindu,Delhi,New Delhi,89211,9.954289e+10,9966866798,rohan.verma@example.in,Driver
998,HDFC100999,HDFC Bank,Ananya Joshi,Female,No,2,Graduate,Salaried,64803,94136,...,0.377,Negative,Hindu,Gujarat,Ahmedabad,532976,6.170000e+11,9103847156,ananya.joshi@example.in,Electrician


In [4]:
#To check the null values
df.isna().sum()

,0
Loan_ID,0
Bank,0
Customer_Name,0
Gender,0
Married,0
Dependents,0
Education,0
Employment_Status,0
Applicant_Income,0
Coapplicant_Income,0


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Loan_ID                      1000 non-null   object 
 1   Bank                         1000 non-null   object 
 2   Customer_Name                1000 non-null   object 
 3   Gender                       1000 non-null   object 
 4   Married                      1000 non-null   object 
 5   Dependents                   1000 non-null   int64  
 6   Education                    1000 non-null   object 
 7   Employment_Status            1000 non-null   object 
 8   Applicant_Income             1000 non-null   int64  
 9   Coapplicant_Income           1000 non-null   int64  
 10  Loan_Amount                  1000 non-null   int64  
 11  Loan_Term_Months             1000 non-null   int64  
 12  Credit_History               1000 non-null   int64  
 13  Property_Area      

In [6]:
#Finding the Per month income of the Applicant
Montly_household_income=df['Applicant_Income']+df['Coapplicant_Income']
print("Montly income per Applicant+Coapplicant\n" ,Montly_household_income)

Montly income per Applicant+Coapplicant
 0       56976
1        1856
2       64553
3       88450
4        9539
        ...  
995     44713
996     70886
997     35729
998    158939
999     22938
Length: 1000, dtype: int64


In [7]:
#Monthly Amount Leaft After all Expense
Monthly_Savings=Montly_household_income-df['Monthly_Expense']
print("Monthly Savings\n" ,Monthly_Savings)

Monthly Savings
 0      26585
1          0
2      39996
3      51700
4       5619
       ...  
995    32814
996    38428
997    12752
998    86563
999     6833
Length: 1000, dtype: int64


In [8]:
#SCALAR MULTIPLICATION
#Growth Rate per Month
growth_rate = 1.05
projected_income = df.Applicant_Income * growth_rate
print("Projected Income\n" ,projected_income)

Projected Income
 0      59824.80
1       1948.80
2      67780.65
3      92872.50
4      10015.95
         ...   
995    46948.65
996    74430.30
997    25611.60
998    68043.15
999    24084.90
Name: Applicant_Income, Length: 1000, dtype: float64


In [9]:
print(f"\nGrowth amount:\n {(projected_income - df.Applicant_Income)}")


Growth amount:
 0      2848.80
1        92.80
2      3227.65
3      4422.50
4       476.95
        ...   
995    2235.65
996    3544.30
997    1219.60
998    3240.15
999    1146.90
Name: Applicant_Income, Length: 1000, dtype: float64


In [10]:
df

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,HDFC100996,HDFC Bank,Simran Kaur,Male,Yes,1,Graduate,Salaried,44713,0,...,10.965,Neutral,Sikh,Tamil Nadu,Coimbatore,6635,3.830000e+11,9350952889,simran.kaur@example.in,Medical Representative
996,HDFC100997,HDFC Bank,Krishna Mehta,Male,No,2,Graduate,Salaried,70886,0,...,3.268,Negative,Hindu,Kerala,Trivandrum,217843,7.040000e+11,9176504718,krishna.mehta@example.in,Customer Support Executive
997,HDFC100998,HDFC Bank,Rohan Verma,Female,No,1,Graduate,Salaried,24392,11337,...,0.703,Positive,Hindu,Delhi,New Delhi,89211,9.954289e+10,9966866798,rohan.verma@example.in,Driver
998,HDFC100999,HDFC Bank,Ananya Joshi,Female,No,2,Graduate,Salaried,64803,94136,...,0.377,Negative,Hindu,Gujarat,Ahmedabad,532976,6.170000e+11,9103847156,ananya.joshi@example.in,Electrician


In [11]:
#Matrix Transpose
matrix = df[[
    'Applicant_Income',
    'Coapplicant_Income',
    'Loan_Amount'
]].values

In [12]:
transposed = matrix.T
print(transposed)

[[  56976    1856   64553 ...   24392   64803   22938]
 [      0       0       0 ...   11337   94136       0]
 [8031545  899361 2387748 ...  301249  719891   61019]]


In [13]:
# Dot Product
features = df[['CIBIL_Score', 'Applicant_Income', 'Employment_Length_Years']].values
weights = np.array([0.5, 0.3, 0.2])

risk_scores = features @ weights
print("Risk Scores\n" ,risk_scores)

Risk Scores
 [17442.5   910.3 19686.6 26874.1  3159.1 12096.4 24715.8   361.5  5599.2
 21691.9  7995.4 11824.5 19341.6  5687.8 16463.2 17187.3  9098.3  3502.2
 11830.5 13367.8 14948.2  4957.4 17234.5 29679.  13913.5 10790.   3148.8
  1143.2 16747.8 13326.5 27274.1  7264.9 28140.1 12097.9 17088.3 10401.1
  8842.9 10476.1  7353.4 39086.9  1243.  18321.5  9437.6 14979.7 18963.6
  8552.8 16195.9 16321.  27757.8 14675.2 28216.1   799.2 24533.3 28632.5
  8602.3  7428.8 10525.5  9785.6 36662.3 12074.  20928.3  8038.3  9354.9
 14078.1 24676.2  9086.  20014.9 20360.4 11256.4 16197.9  4899.   1858.2
 16223.6 16281.2  6771.  11272.4 12394.9 11796.6  3938.7   365.7 21930.
 33979.5  1853.5  1231.5  8767.4  2683.7 27375.8 30922.3  2652.  19133.5
 19146.2  1227.2  6645.4 14051.6 18348.2  2992.2 21192.2 30251.6 25393.5
  1176.9 25166.6 32301.6 10058.5  4492.8 26299.8 22783.1 13494.1 29836.7
  2673.3 18374.9 24117.7 28138.8  1180.4 26591.   1882.  11486.8 23834.7
 45113.6 17762.5 27467.1  1237.5  8614.

In [14]:
#Covariance & Correlation Matrix
fin_cols = ['Applicant_Income', 'Loan_Amount', 'CIBIL_Score', 'Debt_to_Income_Ratio', 'Asset_Value']
cov_matrix = np.cov(df[fin_cols].values.T)
print("Covariance Matrix\n" ,cov_matrix)

Covariance Matrix
 [[ 7.91477548e+08  7.53314000e+08  6.38023346e+04 -6.27524305e+06
   3.40826506e+10]
 [ 7.53314000e+08  6.94333531e+12  3.16092409e+06  5.87761780e+07
   9.82151967e+10]
 [ 6.38023346e+04  3.16092409e+06  5.45183467e+03  3.44266997e+03
   4.02042623e+06]
 [-6.27524305e+06  5.87761780e+07  3.44266997e+03  3.89904162e+06
  -2.63208192e+08]
 [ 3.40826506e+10  9.82151967e+10  4.02042623e+06 -2.63208192e+08
   2.19469831e+12]]


In [15]:
corr_matrix = np.corrcoef(df[fin_cols].values.T)
print("Correlation Matrix\n" ,corr_matrix)

Correlation Matrix
 [[ 1.          0.01016185  0.03071468 -0.11296199  0.81776148]
 [ 0.01016185  1.          0.01624646  0.01129636  0.0251598 ]
 [ 0.03071468  0.01624646  1.          0.02361267  0.03675474]
 [-0.11296199  0.01129636  0.02361267  1.         -0.08997732]
 [ 0.81776148  0.0251598   0.03675474 -0.08997732  1.        ]]


In [16]:
#Scaler Vector Multtiplication
#Rising the Applicant Inome by 7%
df['Applicant_Income'] = df['Applicant_Income'] * 1.07
print(df['Applicant_Income'])

0      60964.32
1       1985.92
2      69071.71
3      94641.50
4      10206.73
         ...   
995    47842.91
996    75848.02
997    26099.44
998    69339.21
999    24543.66
Name: Applicant_Income, Length: 1000, dtype: float64


In [17]:
#Rate of Interset By Bank
#Rate of intrest increase by bank 5%
df['Rate_of_Interest'] = df['Loan_Amount'] * 0.05
print(df['Rate_of_Interest'])

0      401577.25
1       44968.05
2      119387.40
3       32942.80
4        9933.55
         ...    
995    294180.15
996    139011.40
997     15062.45
998     35994.55
999      3050.95
Name: Rate_of_Interest, Length: 1000, dtype: float64
