## LINEAR ALGEBRA

Creating Vectors and Matrices

In [1]:
import numpy as np

In [3]:
# Creating 1D Array and check the shape
v = np.array([1, 2, 3])
print(v.shape)

(3,)


In [ ]:
#Column vector (2D array)
v_col = np.array([[1], [2], [3]])
print(v_col.shape)

(3, 1)


In [5]:
print(v_col)

[[1]
 [2]
 [3]]


In [7]:
# Matrix (2D array)
A = np.array([[1, 2, 3],
            [4, 5, 6]])
print(A.shape)


(2, 3)


In [8]:
print(A)

[[1 2 3]
 [4 5 6]]


# VECTOR & MATRIX ADDITION

In [12]:
# Vector addition
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v_sum = v1 + v2
print(v_sum)


[5 7 9]


In [13]:
# Matrix addition
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print(C)

[[ 6  8]
 [10 12]]


# SCALAR MULTIPLICATION


In [17]:
# Scalar multiplication
v = np.array([1, 2, 3])
c = 2
scaled = c * v
print(scaled)

[2 4 6]


In [19]:
# Matrix scaling
A = np.array([[1, 2], [3, 4]])
scaled_A = 0.5 * A
print(scaled_A)

[[0.5 1. ]
 [1.5 2. ]]


# MATRIX-VECTOR MULTIPLICATION

In [21]:
# Basic matrix-vector multiplication
A = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([[7], [8], [9]])

result = A @ v
print(result)

[[ 50]
 [122]]


In [23]:
#Dot Product
result = np.dot(A, v)
print(result)

[[ 50]
 [122]]


#  MATRIX-MATRIX MULTIPLICATION

In [24]:
A = np.array([[1, 2],      
            [3, 4],
            [5, 6]])

B = np.array([[7, 8, 9],   
            [10, 11, 12]])

C = A @ B 
print(C)

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [26]:
C = np.dot(A, B)
print(C)

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


#  MATRIX TRANSPOSE

In [28]:
A = np.array([[1, 2, 3],
            [4, 5, 6]])
print(A.shape)   


(2, 3)


In [29]:
A_T = A.T
print(A_T.shape)

(3, 2)


In [30]:
print(A_T)

[[1 4]
 [2 5]
 [3 6]]
